[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["curl -fsSL https://bun.sh/install | bash", "export PATH=$HOME/.bun/bin:$PATH", "bun install --frozen-lockfile"]

[phases.build]
cmds = ["export PATH=$HOME/.bun/bin:$PATH", "bun run build"]

[start]
cmd = "$HOME/.bun/bin/bun run start"
